### ISSUE TITLE
Minimal Viable Product

### ISSUE THREAD

**Issue by meyer9** [meyer9/cryptotunes#1]
**TODO**
- [x] Create a React component to render sheet music
- [x] Write function to parse measures to JSON usable by [react-music](https://github.com/FormidableLabs/react-music).
- [ ] Write function to parse measures to JSON usable by [VexFlow](http://www.vexflow.com/).
- [x] Write de-serialization function in solidity for deserializing measures.
- [x] Write serialization function in JS for serializing measures.
- [ ] Overall layout of dApp
- [ ] Voting interface utilizing sheet music renderer
- [ ] Measure creation tool (write measure by entering into text box, display above text box, serialization code for submitting proposal)
- [ ] Claiming interface for claiming "token"

**Comment by meyer9** [comment]
For serialization of measures, here are the structs:
```
struct Note {
    // Step is the time to start the note
    uint8 step;
    // Duration is the end of the note
    uint8 duration;
    // Pitch is the pitch of the note A0 = 0 -> A8 = 96
    uint8 pitch;
}

struct Measure {
    // Notes in the measure
    Note[] notes;
}
```

So a note can be serialized using the following format: `[step][duration][pitch]` where each of those is 1 byte. A measure can be serialized using the following format: `[length notes: uint16][note+]`.

**Comment by meyer9** [comment]
```js
const notes = {
    0: "a",
    1: "a#",
    2: "b",
    3: "c",
    4: "c#",
    5: "d",
    6: "d#",
    7: "e",
    8: "f",
    9: "f#",
    10: "g",
    11: "g#"
}
function deserialize(b) {
    note = notes[b[2] % 12] + ("" + Math.floor(b[2] / 12))
    return [b[0], b[1], note]
}
```

**Comment by meyer9** [comment]
We could require users to have a verified identity with the Wyre SDK.
